name: "Virt Minion ðŸ³Container"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - '*'
    paths:
      - 'custom/virt-minion/*.Dockerfile'

env:
  CONTAINER_NAME: virt-minion
  DOCKERFILE: custom/virt-minion/latest.Dockerfile

jobs:

  build-image:
    runs-on: ubuntu-latest
    name: "Build Virt Minion Container"
    continue-on-error: true

    permissions:
      actions: read
      checks: write
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read

    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@v2

      - name: "Setup DockerFile"
        run: |
          echo " " >> ${{ env.DOCKERFILE }}
          echo "LABEL org.opencontainers.image.source=\"https://github.com/${GITHUB_REPOSITORY}/\"" >> ${{ env.DOCKERFILE }}
          echo "LABEL org.opencontainers.image.url=\"https://github.com/${GITHUB_REPOSITORY}/\"" >> ${{ env.DOCKERFILE }}
          echo "LABEL org.opencontainers.image.documentation=\"https://github.com/${GITHUB_REPOSITORY}/\"" >> ${{ env.DOCKERFILE }}
          echo "LABEL org.opencontainers.image.vendor=\"Unofficial Docker Hub Mirror\"" >> ${{ env.DOCKERFILE }}
          cat  ${{ env.DOCKERFILE }}

      - name: "Docker QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Docker BuildX"
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: "Log into GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build & Publish"
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE }}
          context: custom/virt-minion
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.CONTAINER_NAME }}
